### PR TITLE
First run at IPv6 support for Arista

### PR DESCRIPTION
**Pull request by dopheide-esnet**
Manual testing looks good so far, but I'm not sure about the removal of rules that actually get used.  That's noted by a "DOP" comment in the code.

### CODE REVIEW

**Comment by JustinAzoff** [comment]
This looks really good.  I think it might simplify things a bit if a namedtuple for an ACL was created that contained the (family, name).  That would give you stuff like


    self.logger.info("Setting up %s ACL %s for port %s", acl.family, acl.name, port)

..

    for acl, entries in to_remove.items():    
        cmds.append("%s access-list %s" % (acl.family, acl.name))

..

Just need to create it like this:

```
>>> from collections import namedtuple
>>> ACL = namedtuple("ACL", "family name")
>>> a = ACL("ip6", "foo")
>>> a
ACL(family='ip6', name='foo')
>>> a[0]
'ip6'
>>> a.family
'ip6'
```

Creating something like that and passing the ACL object around should make it even simpler.



I'd switch the logic around in the

    if (iptools.ipv4.validate_ip(src) and family == 'ip') or (iptools.ipv6.validate_ip(src) and family == 'ipv6'):

so that the family check short circuits and prevents calls to iptools.  Though, now that I look at it again it could probably just be something like:

```
family = iptools.something.which_family(src)
for acl in self.acls_by_family[family]:
                cmds.extend([
                    "%s access-list %s" % (acl.family, acl.name),
                    "%d deny %s" % (self.seq, rule),
                ]) 
```


Do you know how many ipv6 acls you can add before the switch blows up? :-)

**Comment by JustinAzoff** [comment]
Oh.. and you're probably right about the removal thing, but if it's using a named tuple the `acl['acl']` can just be set to the new ACL object which will include the family just in case.

**Comment by dopheide-esnet** [comment]
Okay, do I need to do a new pull request or can you see the current version
I've got running?

Also, you need to modify conn-bulk.bro and include v6 there as well:

    const hosts: table[subnet] of PortRange = {[0.0.0.0/0] = PortRange(),
                                               [[::]/0] = PortRange()}
&redef;

**Comment by JustinAzoff** [comment]
I should see updates, but it doesn't look like you've done a push lately.. i don't see any new commits on https://github.com/esnet/dumbno/commits/master either.

**Comment by dopheide-esnet** [comment]
Ah, yeah, I forgot o made that fork before pulling.  I've been pushing to
my Bro branch.  Will take care of that next week.

**Comment by dopheide-esnet** [comment]
Okay, try now.

**Comment by JustinAzoff** [comment]
Ah.. that's more what I had in mind.. It looks like you were working off an older version of dumbno.py so some of the changes undo some recent fixes, but I can fix that I think.

**Comment by dopheide-esnet** [comment]
Cool, let me know when you've merged it as I should probably get the other
fixes running as well (hopefully nothing serious).

-Dop

**Comment by JustinAzoff** [comment]
Well, one of the fixes was to work around a mem leak in jsonrpclib.. so rather important :-)

I just pushed the new branch to https://github.com/ncsa/dumbno/tree/feature-ipv6

Can you test that out?  I moved some things around and tried to simplify things even more, but I may have broken it.

I need to work out how to make it more testable.  The last time I tried I attempted to factor out all the functions that used self.switch, but realized that just moves all the hard to test arista code into a different location.  As you found out, vEOS doesn't support ACLs, so I think the simplest thing to do is build my own fake switch rpc server that looks and acts just like a real switch.

**Comment by JustinAzoff** [comment]
Oh, and I think we should take this discussion to Issue #10

**Pull request closed without merging**
